# pyproject.toml
# 用于集中管理 Python 项目的配置，例如依赖、构建工具和代码质量工具的设置。

[tool.black]
# Black: 不妥协的代码格式化工具
# line-length: 设置每行的最大字符数。
line-length = 120

[tool.flake8]
# Flake8: 代码风格和逻辑检查工具
# max-line-length: 与 black 保持一致，确保格式化和检查规则不冲突。
max-line-length = 120
# exclude: 指定要忽略检查的目录。这些通常是自动生成或与环境相关的文件夹。
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv",
    "venv",
    "env"
]